core/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    
    path('products/', include('products.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)                    

main/urls.py
from django.urls import path
from .views import IndexView, CategoryView

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<str:category_name>/category', CategoryView.as_view(), name='category'),
]

products/urls.py
from .views import new_product, product_detail
from django.urls import path

app_name = "products"
urlpatterns = [
    path("new", new_product, name="new"),
    path("<int:product_id>/detail", product_detail, name="detail"),
   
]

users/urls.py
from .views import SignupView, ProfileView, ProfileUpdateView
from django.urls import path

app_name = "users"
urlpatterns = [
    path("signup", SignupView.as_view(), name="signup"),
    path("profile/<str:username>/", ProfileView.as_view(), name="profile"),
    path("update/", ProfileUpdateView.as_view(), name="update"),
]

main/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from users.models import CustomUser
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150)
    
    def __str__(self):
        return str(self.name)
    
    
    
class Product(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10000000, decimal_places=2)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)
    tg_username = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return str(self.title)
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/')
    
    def __str__(self):
        return str(self.product)
    
class Comments(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)    
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)    
    body = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return f"{self.product} - {self.author}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=17)
    tg_username = models.CharField(max_length=150)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/defaultuser.png')
    
    def __str__(self):
        return str(self.tg_username)

class Saved(models.Model):
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)    
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)    
    body = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return f"{self.product} - {self.author}"

products/forms.py
from django import forms
from .models import Product

class NewProductForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={"allow_multiple_selected":True}), required=False)
    class Meta:
        model = Product
        fields = ("category", "title", "description", "price", "address", "phone_number", "tg_username")

    def save(self, request, commit=True):
        product = self.instance
        product.author = request.user
        super().save(commit)
        return product

users/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("first_name", "username", "email",)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("first_name", "username", "email", "tg_username", "phone", "avatar",)

main/views.py
from django.shortcuts import render
from django.views import View
from products.models import Product, Category
from django.shortcuts import get_object_or_404
# Create your views here.

def all_page_view_category(request):
    categorys = Category.objects.all()
    return {"categorys":categorys}


class IndexView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'index.html', {'products':products})
    
class CategoryView(View):
    def get(self, request, category_name):
        category = get_object_or_404(Category, name=category_name)
        products = Product.objects.filter(category=category)
        return render(request, "category.html", {'products':products, "category":category})

products/views.py
from django.shortcuts import render, redirect
from .forms import NewProductForm
from .models import ProductImage, Product
from django.contrib import messages
from django.shortcuts import get_object_or_404
# Create your views here.


def new_product(request):
    if request.method == "GET":
        form = NewProductForm()
        return render(request, "product_new.html", {"form":form})
    if request.method == "POST":
        form = NewProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            product = form.save(request)
            for image in request.FILES.getlist("images"):
                ProductImage.objects.create(image=image, product=product)
            messages.success(request,"Yangi maxsulot yaratildi")
            return redirect("main:index")
        return render(request, "product_new.html", {"form":form})
        
        
        
def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, "product_detail.html", {"product":product})

users/views.py
from django.shortcuts import render, redirect
from users.forms import SignupForm, UpdateProfileForm
from django.views import View
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Create your views here.


class SignupView(UserPassesTestMixin,View):
    def get(self, request):
        return render(request, "registration/signup.html", {"form":SignupForm()})
    
    def post(self, request):
        form = SignupForm(data=request.POST)
        if form.is_valid:
            form.save()
            messages.success(request, "Muvaffaqiyatli yaratildi")
            return redirect('login')
        return render(request, "registration/signup.html", {"form":form})
            
    def test_func(self):
        user = self.request.user
        if user.is_authenticated:
            return False
        return True
            
class ProfileView(View):
    def get(self, request, username):
        user = get_object_or_404(CustomUser, username=username)
        return render(request, 'profile.html', {"customuser":user})
    
    
class ProfileUpdateView(LoginRequiredMixin, View):
    login_url = "login"
    def get(self, request):
        form = UpdateProfileForm(instance=request.user)
        return render(request, "profile_update.html", {"form":form})  
      
    def post(self, request):
        form = UpdateProfileForm(instance=request.user, data=request.POST, files = request.FILES)
        if form.is_valid:
            form.save()
            messages.success(request, " Ma'lumotlaringiz Muvaffaqiyatli Yangilandi")
            return redirect('users:profile', request.user.username)
        return render(request, "profile_update.html", {"form":form})
            

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        E-Bazar Components

        {% endblock title %}
        
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>


<style>
    img {
        object-fit:contain;
    }
</style>
<body>
    <!-- Navbar Start -->
    <nav class="shadow navbar navbar-expand-lg bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">E-Bazar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-tem">
                <div class="btn-group">
                  <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    Categories
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                    {% for i in  categorys %}
                      <li><a class="dropdown-item" href="{% url 'main:category' i.name %}">{{ i.name }}</a></li>
                      {% endfor %}
                  </ul>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Add Product</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Saveds</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Recently Viewed</a>
              </li>
              
              
            </ul>
              <div class="btn-group">
                <form class="d-flex " role="search">
                  <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                {% if request.user.is_authenticated %}
               
                <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                  <img src="{{ request.user.avatar.url }}" width="35" height="35" class=" rounded" alt="">
                </button>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                  <li><a class="dropdown-item" href="{% url 'users:profile' request.user.username %}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <a href = "{% url 'login' %}" class="btn btn-primary"> Login</a>
                <a href = "{% url "users:signup" %}" class="btn btn-primary"> SignUp</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}

    <div class="container">
        <div style="z-index: 312;" class="shadow-sm position-fixed end-0 bottom-0 mt-4">
            <div style="width: 20rem; opacity:0.9 " class=" m-3 alert alert-info" role="alert">
                Message Sample
            </div>
        </div>
    </div>  
      
    <div class="footer m-5 mb-3 ">
        <center class="text-muted" >Abdurasulov Codes | 2023</center>
    </div>
    <script src="{% static 'script.js' %}" ></script>
</body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} E-Bazar - {{ category }}{% endblock title %}



{% block content %}

    <!-- Product Cart Start -->
    <div class="container">
        <div class=" w-100 mt-4">
            <h4 class="d-block" >Recently Products of {{ category }}</h4>
            <div class="d-flex flex-wrap justify-content-between">
                {% for i in products %}
                <!-- Product Cart Start -->
                <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                    {% if i.productimage_set.exists %}
                    <img height="200" class=" card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="">
                    {% else %}
                    <img height="200" class=" card-img-top" src="{% static 'products/defoultuser.png' %}" alt="">
                    {% endif %}
                    <div class="card-body">
                        <h6 class="align-center card-title">{{ i.title }}</h6>
                        <span class="center card-text"><small>{{ i.price }}</small> $</span>
                        <div class="buttons d-flex flex-wrap justify-content-between ">
                            <i class="bi bi-bookmark-fill"></i> 
                            <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                        </div>
                    </div>
                </div>  
                <!-- Product Cart End -->
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Product Cart End -->
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} E-Bazar - Home{% endblock title %}



{% block content %}

    <!-- Product Cart Start -->
    <div class="container">
        <div class=" w-100 mt-4">
            <h4 class="d-block" >Recently Products</h4>
            <div class="d-flex flex-wrap justify-content-between">
                {% for i in products %}
                <!-- Product Cart Start -->
                <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                    {% if i.productimage_set.exists %}
                    <img height="200" class=" card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="">
                    {% else %}
                    <img height="200" class=" card-img-top" src="{% static 'products/defoultuser.png' %}" alt="">
                    {% endif %}
                    <div class="card-body">
                        <h6 class="align-center card-title">{{ i.title }}</h6>
                        <span class="center card-text"><small>{{ i.price }}</small> $</span>
                        <div class="buttons d-flex flex-wrap justify-content-between ">
                            <i class="bi bi-bookmark-fill"></i> 
                            <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                        </div>
                    </div>
                </div>  
                <!-- Product Cart End -->
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Product Cart End -->
{% endblock content %}

templates/product_detail.html
{% extends "base.html" %}
{% block title %}
   E-Bazar - {{product.title}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class=" w-100 mt-5 ">
        <div class="row shadow-sm ">
            <div class="col-4 p-3">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for picture in product.productimage_set.all  %}
                        {% if picture == product.productimage_set.all.first %}
                        <div class="carousel-item active thumbnail shadow-sm ">
                            <img class="d-block w-100 " width="400" height="270" src="{{picture.image.url}}" alt="">
                        </div>
                        {% else %}
                        <div class="carousel-item thumbnail shadow-sm">
                            <img class="d-block w-100  " width="400" height="270" src="{{picture.image.url}}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
              </div> 
            </div>
            <div class="col-7 p-5 ">
                <h4>{{product.title}}</h4>
                <p class="text-muted"><a href="{% url 'users:profile' product.author.username  %}">@{{product.author.username}}</a> | 25.01.2023</p>
                <p >{{product.description|safe}}</p>
                <div class="contact mt-4 ">
                    {% if request.user == product.author %}
                    <a class="btn btn-warning" href="#">Edit details</a>
                    {% endif %}
                    <a class="btn btn-primary" href="mailto:{{product.author.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{product.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{product.tg_username}}">Telegram</a>
                </div>
            </div>
        </div>
        <div class="row ">  
            <div class="col-8 mt-5" >
                <h6  >In This Category</h6> 
                <div class="d-flex flex-wrap justify-content-between">
                    {% for i in product.category.product_set.all %}
                    {% if product != i %}
                    <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 14rem;" >
                        <img height="190" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                        <div class="card-body">
                            <h6 class="align-center card-title"> {{i.title}}</h6>
                            <span class="center card-text">${{i.price}}</span>
                            <div class="buttons d-flex flex-wrap justify-content-between ">
                                <i class="bi bi-bookmark-fill"></i> 
                                <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}  
                    {% endfor %}
                </div>
            </div>
            <div class="col-4 mt-5 shadow-sm ">
                <h6 class="pt-2" >Add comment</h6>
                <form action="" method="post" class="input-group"> {% csrf_token %}
                    <input class="form-control" name="body" type="text" placeholder="Type your comment..." aria-describedby="'button-addon" >
                    <button class="btn btn-outline-success" type="submit" id="button-addon">Send</button>
                </form>  
                <hr>
                <h6>Comments</h6>
                {% for comment in product.comment_set.all %}
                <small class="text-muted" >@{{comment.author}} | {{comment.date}}</small>
                <p>{{comment.body}} 
                    {% if request.user == comment.author %}
                        <small><a href="{% url 'products:comment_delete' product.id comment.id   %}">delete</a></small>  
                    {% endif %}
                     
                </p>  
                {% endfor %}
            </div>
        </div>

</div>
</div>
{% endblock content %}

templates/product_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
New Product
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col mt-5">
        </div>
        <div class="col-6 mt-6">
            <h2>
                New Product

            </h2>
            <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                {% comment %} [ enctype="multipart/form-data" ] => formadan fayllar yuborilayotganda barcha fayllarni
                qabul qilish uchun qo'yiladi {% endcomment %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary"> Create </button>
                <a class="btn btn-secondary" href="{% url 'main:index' %}"> Back to Home
                </a>
            </form>

        </div>
        <div class="col">
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    E-Bazar - {{customuser}}
{% endblock title %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 card mt-5 ">
            <div class="row">
                <div class="col-2 m-3">
                    <img class="img-thumbnail" width="150" height="150" src="{{ customuser.avatar.url }}" alt="profile image">
                </div>
                <div class="col-8 m-3">
                    <h2>{{ customuser.get_full_name }}</h2>
                    <p class="text-muted" >@{{ customuser.username }} | {{ customuser.email }}</p>
                    {% if customuser == request.user %}
                    <a class="btn btn-warning" href="{% url 'users:update' %}">Edit details</a>
                    <a class="btn btn-danger" href="{% url 'password_change' %}">Update Password</a>
                    {% endif %}
                    <a class="btn btn-primary" href ="mailto:{{customuser.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{customuser.phone}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{customuser.tg_username}}">Telegram</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Product Cart Start -->
<div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products of @{{ customuser.username }}</h4>
        {% if not customuser.product_set.exists %}
        <center class="text-muted"> Ushbu Userning birorta mahsuloti yo'q </center>
        {% else %}
        <div class="d-flex flex-wrap justify-content-between">
            <!-- Product Cart Start -->
            {% for i in customuser.product_set.all %}
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{ i.productimage_set.all.first.image.url }}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="{% static 'products/defoultuser.png' %}" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{ i.title }}</h6>
                    <span class="center card-text"><small>{{ i.price }}</small> $</span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i> 
                        <a href="#" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            {% endfor %}
            <!-- Product Cart End -->
          
        </div>
        {% endif %}
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}

templates/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Profile Update - {{ request.user }}
{% endblock title %}



{% block content %}

<div class="container">
<div class="row mt-5">
    <div class="col mt-5">
</div>
    <div class="col-6 mt-6">
    <h2> 
Profile Update - {{ request.user }}
</h2>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary"> Update </button>
                <a class="btn btn-secondary" href="{% url 'users:profile' request.user.username %}"> Back to Profile </a>
            </form>

</div>
    <div class="col">
    </div>
</div>
</div>

{% endblock content %}